export const ICON_CATEGORIES = {
  frontend: [
    { name: 'react', label: 'React' },
    { name: 'nextjs', label: 'Next.js' },
    { name: 'typescript', label: 'TypeScript' },
    { name: 'javascript', label: 'JavaScript' },
    { name: 'tailwind', label: 'Tailwind CSS' },
    { name: 'vite', label: 'Vite' },
    { name: 'html', label: 'HTML5' },
    { name: 'css', label: 'CSS3' },
  ],
  backend: [
    { name: 'nodejs', label: 'Node.js' },
    { name: 'express', label: 'Express.js' },
    { name: 'fastapi', label: 'FastAPI' },
    { name: 'jwt', label: 'JWT' },
    { name: 'mongoose', label: 'Mongoose' },
    { name: 'rest', label: 'REST API' },
    { name: 'security', label: 'Security' },
  ],
  database: [
    { name: 'mongodb', label: 'MongoDB' },
    { name: 'mysql', label: 'MySQL' },
    { name: 'postgresql', label: 'PostgreSQL' },
    { name: 'supabase', label: 'Supabase' },
  ],
  devops: [
    { name: 'docker', label: 'Docker' },
    { name: 'nginx', label: 'Nginx' },
    { name: 'githubactions', label: 'GitHub Actions' },
    { name: 'pm2', label: 'PM2' },
    { name: 'git', label: 'Git' },
    { name: 'github', label: 'GitHub' },
  ],
  cloud: [
    { name: 'aws', label: 'AWS' },
    { name: 'cloudflare', label: 'Cloudflare' },
    { name: 'vercel', label: 'Vercel' },
    { name: 'render', label: 'Render' },
  ],
  others: [
    { name: 'python', label: 'Python' },
    { name: 'java', label: 'Java' },
    { name: 'php', label: 'PHP' },
    { name: 'postman', label: 'Postman' },
    { name: 'figma', label: 'Figma' },
    { name: 'vscode', label: 'VS Code' },
    { name: 'npm', label: 'NPM' },
    { name: 'bash', label: 'Bash' },
    { name: 'markdown', label: 'Markdown' },
  ],
};